# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
